### ISSUE TITLE
Do you have any plans to support Rails 5?

### ISSUE THREAD

**Issue by tumayun** [discourse/rails_multisite#5]
Is it possible to support Rails 5 in the near future?

**Comment by SamSaffron** [comment]
totally support any PRs for it, totally want it to work in 5. We will fix
it as soon as we upgrade to 5

**Comment by tgxworld** [comment]
Closed by https://github.com/discourse/rails_multisite/commit/a4858e32ca1ae4ed7ac5e96b7311d959aa1e4959
