### ISSUE TITLE
Hostname config in discourse

### ISSUE THREAD

**Issue by James9074** [discourse/rails_multisite#8]
In the context of discourse, as per this line: https://github.com/discourse/discourse/blob/master/lib/discourse.rb#L215 , how would I go about setting the [host_names](https://github.com/discourse/rails_multisite/blob/master/lib/rails_multisite/connection_management.rb#L169) config setting? It looks like discourse has the config sample yml, but no multisite config file, so I can't figure out what's going on.

Somewhere, either on the Discord side (`forced_hostname` being set to www.example.com) or within multisite it's breaking down and returning `www.example.com`. Any thoughts or is this likely just my config being bad somewhere?

**Comment by SamSaffron** [comment]
multisite is covered here: https://meta.discourse.org/t/multisite-configuration-with-docker/14084
